### PR TITLE
You can remove the glitch test line.

### PR DESCRIPTION
**Pull request by sgmedev**

### CODE REVIEW

**Comment by sgmedev** [comment]
Maybe remove on pull request from the action

**Comment by arj101** [comment]
?

**Comment by arj101** [comment]
@TheSuperGamer20578  What are you trying to say?

**Comment by sgmedev** [comment]
In your actions yml file for syncing you had it do the check on pull requests wich you dont want it just says fail when someone makes a PR i think i have updated this PR to fix it

**Comment by arj101** [comment]
How can i preview it?

**Comment by arj101** [comment]
@TheSuperGamer20578  Thanks!

**Comment by sgmedev** [comment]
@arj101  i am trying to say it runs the action on PRs so when someone makes a PR it says it failed the check

**Comment by arj101** [comment]
Oh!

**Comment by arj101** [comment]
That's true, i need to make it so that it merges on merging a PR

**Comment by arj101** [comment]
Do you have any idea?

**Comment by arj101** [comment]
@TheSuperGamer20578

**Pull request merged**
