### PR TITLE
Add Duck Controls & Enhance Timer

### PR DESCRIPTION
**Pull request by Lemmings42**

### CODE REVIEW

**Comment by arj101** [comment]
duck?

**Comment by Lemmings42** [comment]
Yeah, I accidentally separated duck pull requests, so the duck. command is in the other one :/

**Comment by arj101** [comment]
Maximum game timer delay of 24 hours! ?

**Comment by Lemmings42** [comment]
Yeah, you can change that if you want
It was  just convenient

**Comment by arj101** [comment]
Okay, np

**Comment by arj101** [comment]
Merging now, thanks for the PR.

**Comment by arj101** [comment]
I'm having problem with the game redirect when the timer finishes

**Comment by arj101** [comment]
can you add the changes to my latest commit?

**Comment by arj101** [comment]
Also github shows that the whole code in sketch.js was removed and rewritten

**Comment by arj101** [comment]
So the commit has been reverted

**Comment by Lemmings42** [comment]
It doesn't show that for me... and the formatting shouldn't break it. Ill look at that

**Comment by arj101** [comment]
Is it because I had a lot of commits after your PR?

**Comment by Lemmings42** [comment]
Maybe
For me it just shows the lines when I call the timer and the function to format them

**Comment by arj101** [comment]
Can you have a look at tye `Files Changed` tab in this PR?

**Comment by Lemmings42** [comment]
Oh that's weird

**Comment by arj101** [comment]
Yeah

**Comment by Lemmings42** [comment]
In that case,  Just drop this code into the other manually?
Neither of the commits show that

**Comment by arj101** [comment]
I don't know really what you changed to find the changes.

**Comment by Lemmings42** [comment]
just check the actual commits

**Comment by arj101** [comment]
Is it just calling `duck` and `unduck`?

**Comment by arj101** [comment]
> In that case, Just drop this code into the other manually?
> Neither of the commits show that

Okay

**Comment by Lemmings42** [comment]
yep. Also, your merge commit seems to be the thing deleting everything

**Comment by arj101** [comment]
I will check the commits  :)

**Comment by arj101** [comment]
I will try to add everything manually then.

**Comment by arj101** [comment]
Added the changes manually!

**Comment by Lemmings42** [comment]
Okay!

**Comment by arj101** [comment]
I will merge the other one a bit later.

**Pull request merged**
